### PR TITLE
At this point I think it is easier to make another pr

### PR DESCRIPTION
**Pull request by d-air1**
Sorry for making yet another pr because my git skills suck, but it honestly just seemed easier than dealing with all of those faulty commits of mine.

### CODE REVIEW

**Comment by soreau** [comment]
Have you cast to int for all QPoints in the file?

**Comment by d-air1** [comment]
Yes

**Comment by soreau** [comment]
It seems like this is a change in Qt that caused this rather than python.. would be nice to know which version.

**Comment by d-air1** [comment]
All except for one. I'll certainly try to look up what the change in Qt was. I remember reading about the error that I was getting and people saying it started happening upon updating python, but that was probably unrelated.

**Comment by d-air1** [comment]
Anyways the one QPoint that isn't being cast to int is the one on line 374 where you seem to be grabbing some type of x,y coordinate. The only reason we didn't cast that one to int is because it was already taken car of on line 367.

**Comment by soreau** [comment]
Ok, I have applied your changes and plan to run for some days to test them.

**Comment by soreau** [comment]
> Anyways the one QPoint that isn't being cast to int is the one on line 374 where you seem to be grabbing some type of x,y coordinate.

It's rendering the version text for the splash at version_pos.

> The only reason we didn't cast that one to int is because it was already taken car of on line 367.

**Comment by d-air1** [comment]
Okay thanks for the explanation. I found a reference to QPointF in the Qt documentation which I believe does what you were doing before for version 6.3, but the current version of pyqt5 that is installed on arch is 5.15.6, so I'm not sure where exactly the breaking change occured, but I'll keep looking.

**Comment by soreau** [comment]
> Okay thanks for the explanation.

Yea it draws black at xy + 1 and white at xy + 0 on top for a pop effect.

> I found a reference to QPointF in the Qt documentation which I believe does what you were doing before for version 6.3, but the current version of pyqt5 that is installed on arch is 5.15.6, so I'm not sure where exactly the breaking change occured, but I'll keep looking.

It's not a big deal, your patch looks like the right way forward.

**Comment by soreau** [comment]
I have found another setMaximum() without the cast [here](https://github.com/soreau/catt-qt/blob/master/cattqt/cattqt.py#L858).

**Comment by d-air1** [comment]
Alright, I'll make that change. I also tested the app while replacing Qpoint with QpointF. It works, but I'm not sure if it will be worth making the change if we still have to cast some other variables though.

**Comment by soreau** [comment]
Precision isn't really needed in these cases though maybe it would look cleaner to switch to QPointF. I'll leave it up to you to decide.

**Comment by d-air1** [comment]
I'll make the switch just so it looks cleaner then.

**Comment by d-air1** [comment]
I added the int cast on that other setMaximum call and I have switched to using QPointF.

**Comment by soreau** [comment]
Alright, I will test a bit more. Thanks for the update.

**Comment by d-air1** [comment]
My pleasure, let me know if you find anything else.

**Comment by soreau** [comment]
Thanks!

**Comment by d-air1** [comment]
No problem and thank you for working with me.

**Pull request merged**
